---
title: 'Final Exam'
author: 'Phil 444'
date: 'April 26, 2024'
execute:
  warning: false
  message: false
  cache: true
format:
    html:
      toc: false
      mainfont: SF Pro Rounded
    pdf: 
      format: letter
      keep-tex: true
      geometry:
        - margin=25mm
      mainfont: Scala Pro
      sansfont: Scala Sans Pro
      mainfontoptions: Scale = MatchLowercase
      fontsize: 12pt
      linkcolor: black
      link-citations: true
      
      include-in-header: 
        text: |
          \usepackage{fancyhdr}
          \usepackage{titling}
          \pagestyle{fancy}
          \pagenumbering{gobble}
          \fancyhf{}
          \renewcommand\maketitle{
            \fancyhead[C]{
              \thetitle
              \ifx \theauthor\empty  \else \ – \theauthor \fi
              \ifx \thedate\empty  \else \ – \thedate \ \fi
            }
          }
          \fancyfoot[C]{\thepage}
---

For any question asking for a verbal answer (e.g., explain this notion, or this constraint), you should answer in about **250** words. These are _short answer_ questions, not essays, and the aim is to either (a) simply describe a concept or idea, or (b) present one reason for or against some notion. Don't try to write a five paragraph essay for each one. On the other hand, if your answer is much under 250 words, try explaining a bit more of the background; probably that means that you are presupposing something that we want you to make explicit.

1. Describe an example where Sen's Condition L (Liberalism) and Condition P (Pareto) conflict.
2. Describe an example of a **focal point** in Schelling's sense.
3. What is the difference between weak dominance and strict dominance? Describe an example where the two notions come apart.
4. In @tbl-dom, what will be the result if both players use iterated deletion of strictly dominated strategies to decide what to do? (In each cell, Row's payouts are first, and Column's are second.)

|       |  **W**  |  **X**  |  **Y**  |  **Z**  |
|:-----:|:---:|:---:|:---:|:---:|
| **A** | 6,3 | 0,4 | 2,7 | 1,3 |
| **B** | 5,5 | 5,6 | 2,3 | 5,8 |
| **C** | 2,2 | 3,7 | 7,2 | 3,5 |
| **D** | 4,7 | 0,4 | 1,6 | 2,2 |

: Game table for Q4 {#tbl-dom}

5. In @fig-back, what will be the result if all players uses backward induction to solve the problem? (At each terminal node, the payouts are player 1's, then player 2's, then player 3's. Each player moves once; first player 1, then player 2, then player 3.)

```{r engine="tikz"}
#| fig-format: png
#| echo: false
#| label: fig-back
#| fig.cap: "Tree for Q5"


\usetikzlibrary{calc}

\begin{tikzpicture}
  \tikzset{
    % Three node styles for game trees: solid and hollow and square
      solid node/.style={circle,draw,inner sep=1.5,fill=black},
      hollow node/.style={circle,draw,inner sep=1.5},
      square node/.style={rectangle,draw, inner sep = 1, fill = black}
      }

  % Specify spacing for each level of the tree
  \tikzstyle{level 1}=[level distance=15mm,sibling distance=40mm]
  \tikzstyle{level 2}=[level distance=15mm,sibling distance=20mm]
  \tikzstyle{level 3}=[level distance=15mm,sibling distance=10mm]

  \node[hollow node,label=above:{P1}]{}
    child { node [solid node,label=left:{P2}] {}
      child { node [solid node,label=left:{P3}] {}
        child { node [] {1,1,3}
            edge from parent
            node[left]{L}}
        child { node [] {2,2,2}
            edge from parent
            node[right]{R}}
        edge from parent
            node[left]{L}
        }
      child { node [solid node,label=right:{P3}] {}
        child { node [] {3,3,0}
            edge from parent
            node[left]{L}}
        child { node [] {4,0,1}
            edge from parent
            node[right]{R}}
        edge from parent
            node[right]{R}
        }        
      edge from parent
        node[left]{L}
    }
    child { node [solid node,label=right:{P2}] {}
      child { node [solid node,label=left:{P3}] {}
        child { node [] {5,3,5}
            edge from parent
            node[left]{L}}
        child { node [] {6,1,4}
            edge from parent
            node[right]{R}}
        edge from parent
            node[left]{L}
        }
      child { node [solid node,label=right:{P3}] {}
        child { node [] {7,2,2}
            edge from parent
            node[left]{L}}
        child { node [] {0,4,3}
            edge from parent
            node[right]{R}}
        edge from parent
            node[right]{R}
        }        
      edge from parent
        node[right]{R}
    }
    
    ;
    \end{tikzpicture}
```

6. What is the human capital theory of the explanation of the college wage premium? Describe one objection to it. (You do not have to answer the objection.)
