---
subtitle: "444 Lecture 5"
title: "Brown on Justified Group Belief"
author: "Brian Weatherson"
date: "January 30 2024"
format:
  revealjs:
    theme:
      - default
      - robot-lung.scss
    margin: 0.15
    center: false
    self-contained: true
    slide-number: c/t
    show-slide-number: all
#include-in-header:
#  file: border.html
keep-md: false
tbl-cap-location: bottom
code-block-background: true
---

# A Simple Theory

## A Simple Theory

A group G is justified in believing p just in case the majority of the **operative members** of the group justifiably believes p.

## Plan

1. Go over doctrinal paradox again
2. This might make it too easy to have justified group belief - nurses case, and (final) security guards case.

# Doctrinal Paradox

## Doctrinal Paradox

Even if every member of a group has coherent views, the majority opinion might be incoherent.

This can happen in really simple cases.

Imagine a house has been broken into, and the police suspect that Sherlock Holmes, or his sidekick John Watson, is responsible.

## Some Propositions

- 1 = Exactly one person broke into the house.
- S = Sherlock broke into the house.
- W = Watson broke into the house.

## Three Police Officers

A believes it was Sherlock acting alone, so believes 1 and S.

B believes it was Watson acting alone, so believes 1 and W.

C believes it was both Sherlock and Watson acting together, so believes S and W.

## Majority View

What does the majority believe?

- Two out of three believe 1, so they believe it.
- Two out of three believe S, so they believe it.
- Two out of three believe W, so they believe it.
- So they believe Sherlock broke it, and Watson broke in, and exactly one person broke in. Oops!

## Probability

You might think that the problem here is using on/off beliefs, when we should be using probabilities.

Hold that thought - we'll come back to it on Thursday.

# Too Easy

## Nurses Case

This one is from Lackey, and the theoretical questions it raises are very complicated.

- Each nurse neglects their duty, but what they are doing is redundant.
- They also neglect to check in with the others.
- So while they reasonably believe that the patient is safe, they wouldn't if they pooled their evidence.

## Evidence Collection

The fact that this case involves a group is a complication, so let's start with the individual case first.

Let's say Holmes has excellent evidence that Moriarty planted the bomb.

There is defeating evidence for this inside an envelope he has just been given.

But he's so excited at proving Moriarty is guilty that he goes off to celebrate, and doesn't open the envelope.

## Philosophical Questions

1. Does Holmes have a justified (rational) belief that Moriarty planted the bomb?
2. Would it be different Holmes was not a private detective, but an official detective, i.e., a police officer?
3. Would it be different if it wasn't Holmes, but a group, like the London police, charged with investigating crimes?

## Evidence Checking

These are really hard problems, that go to the heart of what rational *belief* is. 

Is it about rationally responding to the evidence the world gives you, or is it about rationally engaging with the world in the right way that you get as good a picture of the world as possible? 

Or somewhere in between?

Anyway, Lackey is really committed to evidence collection mattering.

## Guards Case

This one is really fascinating, and gets to a surprising big picture problem.

Start with a background point about evidence.

Sometimes evidence isn't for or against a proposition directly, but is against the significance of other evidence.

Evidence that a machine is broken is evidence that the evidence it provides is worthless.

## Guards Case

Each guard has two pieces of evidence.

1. Direct evidence for p that's on its own rather good.
2. Evidence that some other guard's evidence is misleading.

Lackey: Each guard justifiably believes that p, but the group does not.

## Evidence Pooling

I think the picture behind Lackey's view here is something like the following.

1. Evidence pooling is good.
2. If we have a justified belief, it should persist by doing this good thing, namely pooling our evidence.

## Lackey's Positive View

The group is justified in believing p just in case 

1. Enough of the operative members of the group are justified in believing p; and
2. The reasons each of them have are not, collectively, too incoherent.

Roughly, the beliefs would survive pooling.

# Input Conditions

## Belief and Evidence

For individuals, justified beliefs are based on evidence that they have.

The same should be true for groups.

But what is it for groups to have evidence?

This is where Brown's objections start.

## Three Options

The group G has evidence E just in case

1. All the operative members have E.
2. Most of the operative members have E.
3. Some of the operative members have E. 
 
All of these have problems.

## All the Members

If the groups only possesses evidence that is universally shared, they will very rarely have enough evidence to justify belief.

Imagine that E1, E2, and E3 are all excellent pieces of evidence that p is true, and they reinforce each other. So having any two of them makes p really likely.

## All The Members

Now imagine a three person group, A, B and C, as follows:

- A has E1 and E2, and so justifiably believes p.
- B has E1 and E3, and so justifiably believes p.
- C has E2 and E3, and so justifiably believes p.

There is **no** evidence they all have, so on this view they don't have enough evidence. That seems bad, because they are all really justified in believing that p, for non-conflicting reasons.

## Most of the Members

The point of Brown's really complicated train example is to undermine this option.

The example makes a bit more sense if you're familiar with the train system in south-eastern Scotland, which I assume means it was easy enough for somewhere between 0 and 2 people in this class to follow.

Let's do a simpler case.

## Evidence that Clicks

There has been a crime, a poisoning of a foreign spy, and there is no reason to suspect Moriarty. Everyone assumes that he has neither the means, nor the motive, nor the opportunity, to commit the crime.

Moriarty is a super criminal, so if he had the means (i.e., access to the poison), motive (i.e., reason to poison the spy), and opportunity (i.e., access to the spy), he likely did it. But most people think he had none of the three, so he's probably innocent (of this crime).

Three detectives, A, B, and C, are assigned to the case.

## Most of the Members

- A has evidence that Moriarty has means and motive, but thinks (like everyone outside the group) that he didn't have the opportunity.
- B has evidence that Moriarty has means and opportunity, but thinks (like everyone outside the group) that he didn't have the motive.
- C has evidence that Moriarty has motive and opportunity, but thinks (like everyone outside the group) that he didn't have the motive.
- What does the group think?

---

Brown argues that the 'most of the members' view has the following bad consequence.

1. Since for each of means, motive, and opportunity, it's part of the majority's evidence that Moriarty has it, the group's evidence is that Moriarty is likely guilty.
2. But the group doesn't believe this, since *no one* in the group believes it.
3. Indeed, they believe Moriarty is innocent.
4. So the group is irrational, believing something that goes against their evidence.
5. But the group doesn't seem irrational!

## Some of the Members

So what about option 3. This is what Brown's example of Professor X is supposed to rule out.

Again, the case uses some terminology that makes more sense in Scotland than America, so let's go with a simpler one.

## Criminal Investigation

In this case imagine that most of the investigators are convinced, on reasonable grounds, that Moriarty carried out the crime.

But one investigator gets conclusive proof (maybe CCTV footage or something similar) that it was someone else, and so Moriarty didn't do it. (At least, didn't do it in person.

--

Brown argues that the 'some of the members' view has the following bad consequence.

1. Since this one investigator has conclusive proof that someone else did it, that is part of the group's evidence.
2. But the group believes that Moriarty did it; that's what the vast majority think.
3. So, the group is being irrational; they are not following their evidence.
4. That seems wrong, since everyone in the group is rational.

## Summary

Brown argues this is bad news for reductive, or what she calls **summative** accounts of group evidence.

There's no easy way to relate what the evidence of each member is to what evidence the group has.

# Brown's Objection to Lackey

## Brown's Objection

After all that, the actual objection to Lackey's view is fairly simple.

1. The right view of justified group belief will say that groups are justified only when they are reacting to their evidence.
2. There is no model of evidence that combines with Lackey's view to imply that groups are justified only when they are reacting to their evidence.
3. Therefore, Lackey's view is wrong.

## Premise 2

The point of the last section was really to defend premise 2.

- Whether you take group evidence to be evidence all the group has, or most of the group has, or some of the group has, you don't get the right result.
- I won't go over all those cases again, but if you were sceptical of any one of those cases, Brown's argument isn't working.

## Premise 1

1. The right view of justified group belief will say that groups are justified only when they are reacting to their evidence.

What Brown is saying here is that justified group beliefs should have the same input conditions as justified individual beliefs.

And she's also assuming (I think plausibly!) that the input condition for individual justified belief is that it is evidence based.

## Asymmetry Responses

One thing Lackey could say here is that it she doesn't care about group beliefs being just like individual beliefs.

Maybe individual beliefs should be evidence-responsive, but group beliefs need not be.

Given how much weight Lackey puts on individual beliefs and group beliefs having the same output conditions, this doesn't seem great.

## Input Conditions

Let's step back a bit and think about individual beliefs. There are two things you might care about in input conditions.

1. Evidence-responsiveness
2. Truth-conduciveness

These aren't quite the same thing.

## Two Conditions

A belief forming process is evidence-responsive if it involves taking in evidence, and responding in the right kind of way to that evidence, for some natural understanding of 'evidence'.

A belief forming process is truth-conducive if it reliably generates truths.

These aren't the same thing in theory, even if we think for ordinary humans they are the same thing in practice.

## Two Conditions

If you think that trusting religious authorities (a) is not a form of evidence-responsiveness, and (b) is truth-conducive, you'll think it's true that a method can be truth-conducive without being evidence-responsive.

I don't really think either of those things, but plenty of religious traditions do, and they don't seem incoherent.

And that's enough to say the two notions, truth-conduciveness and evidence-responsiveness, are logically distinct.

## Brown's Paper

One thing I found confusing about Brown's paper is that I normally understand 'direction of fit' talk as being about whether belief forming practices are truth-conducive, but she's using it to talk about evidence-responsiveness.

This is a terminological issue that was notable to me and *maybe* to a handful of other people here, and while I'm more than happy to take questions on it, I'm just going to set it aside.

## Truth and Evidence

OK, here's a view that's broadly in the spirit of Lackey's that you could have.

1. For ordinary individual humans, the only reliable way to get to the truth is to follow the evidence. That is, it is to follow the evidence *that one has*.
2. But for groups, there is another way. It is to be composed of rational, evidence-seeking, evidence-following, individuals, and to compose their beliefs into a group-belief in the right kind of way.

## Truth and Evidence

There are lots of ways you could criticise this view; I'm certainly not meaning to endorse it.

For one thing, it sort of requires thinking of evidence-responsiveness as a means to the end, where the end is true beliefs, rather than something valuable in itself. And I'm not sure I like that way of thinking about evidence. But it's a view.

# Brown's View

## Brown's Positive View

We don't get as much detail in this paper on Brown's positive view; there's more in the longer book, but I don't want to get into those details.

What Brown gives you is more of a recipe than a full theory.

## Plural Subject

The simplest way to think of Brown's view is as being in the same family as Gilbert's.

The group that has beliefs is a kind of plural subject.

What does it mean to say that group has evidence?

It means the group has some content that plays the same role for it as evidence typically plays for other (i.e., individual) subjects.

## Very Big Picture

The more expansive one's metaphysics of groups, the more symmetries you can have between groups and individuals.

Brown lets group evidence and group belief float free of the evidence and beliefs of the members of the group. That's what she means by rejecting "summative" and "neo-summative" accounts.

That makes groups weird, kind of spooky, things.

But what she gets from that is a much closer symmetry between groups and individuals.

# For Next Time

## For Next Time

We'll go from talking about beliefs to talking about probabilities.

This might seem like it will make some of the problems easier.

But instead there will be whole new problems!